### ISSUE TITLE
Adding an inexistent term in `tax_query` leads to broken DSL syntax

### ISSUE THREAD

**Issue by moraleida** [alleyinteractive/es-wp-query#102]
### Description of the bug

The filtering to remove empty term queries that happens in [class-es-wp-tax-query.php#L109](https://github.com/alleyinteractive/es-wp-query/blob/main/class-es-wp-tax-query.php#L109) does not re-sort the resulting `$filters` array, which can in some cases lead to arrays not being `0` based.

When a non-0-based array gets passed as part of a query to `wp_json_encode` in [adapters/searchpress.php#L23](https://github.com/alleyinteractive/es-wp-query/blob/main/adapters/searchpress.php#L23) it gets transformed into a JSON object with numeric keys, instead of the expected list of objects.

This creates invalid DSL syntax.

### Steps To Reproduce

In an mu-plugin, hook into `pre_get_posts` and add separate tax queries searching for term slugs, first one that doesn't exist and then another one which exists in the database.

Run a searchpress query.

When the DB query in [transform_query](https://github.com/alleyinteractive/es-wp-query/blob/main/class-es-wp-tax-query.php#L315) runs and returns an empty value for the first term, it will be removed from the array without sorting.

This will create invalid syntax and a 400 response from Elasticsearch.

**Comment by mboynes** [comment]
Do you think this is any more complicated than changing that line to this?

```php
$filters = array_values( array_filter( $filters ) );
```

**Comment by moraleida** [comment]
It's not really complicated. 

either 
```php
$filters = array_values( array_filter( $filters ) );
```
or 
```php
$filters = array_filter( $filters );
sort( $filters );
```

Should have the same effect and fix this.

**Comment by moraleida** [comment]
That said, there's a case to be made here also that the DB checks that happen in [transform_query](https://github.com/alleyinteractive/es-wp-query/blob/main/class-es-wp-tax-query.php#L315) are unnecessary, with the possible exception of the `term_taxonomy_id` transformation if that field is not present in Elasticsearch.

I may be missing some context, but It feels counter intuitive to use raw `wpdb` queries to build the Elasticsearch DSL, given that the ES query will not fail if a term doesn't exist.

**Comment by mboynes** [comment]
It could definitely be optimized, but it will require a bit of a refactor.

The reason `transform_query()` runs is to normalize the parent terms to term ids to join them with child term ids so there's one single `terms` query. That could be refactored to a bool should query, e.g. (I think):

```json
{
  "bool": {
    "minimum_should_match": 1,
    "should": [
      "terms": { "term_id": [ ... ] },
      "terms": { "slug": [ ... ] }
    ]
  }
}
```

slugs should be safe to use in a query like this, but I'm not sure names are. ES_WP_Query doesn't enforce how `name` is indexed in the mapping, as a text vs keyword field, so if `name` is a text field it could produce unexpected results (e.g. if you have a tag `News` and another `Breaking News`, I _think_ that a query for the `News` tag would yield results for both tags, but that needs to be confirmed).

All that said, I favor both approaches here. We can start with `$filters = array_values( array_filter( $filters ) );`, as that's valuable regardless, and then we can look at refactoring `transform_query()` to further optimize it.

**Comment by mboynes** [comment]
I took a deeper dive into the code and I was mistaken, `transform_query()` can't be optimized into a `bool.should` query. The terms need to be normalized to `term_id`s in order to [later query for the child terms](https://github.com/alleyinteractive/es-wp-query/blob/1c7402b2f92fd9327e0189a39c85c2ab8b6ea2ec/class-es-wp-tax-query.php#L278). If we have term slugs, we can't get descendants without knowing the slug's `term_id`. Since we're converting the slugs (or other field) to term ids _anyway_, using those in the query alongside the children is actually the most optimal solution.

I did notice a bug along the way, though, which is that if we're querying by `name`, [the name is getting sanitized with dashes before the query runs](https://github.com/alleyinteractive/es-wp-query/blob/1c7402b2f92fd9327e0189a39c85c2ab8b6ea2ec/class-es-wp-tax-query.php#L316). I filed a separate issue for that (#103).
